name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04

    container:
      image: ros:humble  # ROS 2 Humble のコンテナイメージを使用

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # リポジトリからコードをチェックアウト

      - name: Set up ROS 2 environment
        shell: bash
        run: |
          # ROS 2 環境をセットアップ
          source /opt/ros/humble/setup.bash

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions  # colconのインストール

      - name: Build ROS 2 workspace
        run: |
          mkdir -p /root/ros2_ws/src
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash  # ROS 2 環境を再設定
          colcon build  # ROS 2 ワークスペースのビルド

      - name: Run tests
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash  # ROS 2 環境を再設定
          source /root/ros2_ws/install/setup.bash  # ROS 2 ワークスペースのセットアップ
          timeout 10 ros2 launch mypkg talk_listen.launch.py > /tmp/mypkg.log  # テスト実行


